# Generated by Django 3.1.2 on 2020-12-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentReq',
            fields=[
                ('AID', models.AutoField(primary_key=True, serialize=False)),
                ('DeviceID', models.IntegerField(default='1')),
                ('UserName', models.CharField(max_length=20)),
                ('Latitude', models.CharField(max_length=30)),
                ('Longitude', models.CharField(max_length=30)),
                ('Time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Hospital_Name', models.CharField(max_length=50)),
                ('Latitude', models.CharField(max_length=10)),
                ('Longitude', models.CharField(max_length=10)),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
    ]
