# Generated by Django 3.1.2 on 2020-12-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='zipcode',
            field=models.IntegerField(max_length=6, null=True),
        ),
    ]
