# Generated by Django 3.1.2 on 2020-12-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locater', '0002_hospital_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('LID', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=15)),
                ('password', models.TextField(max_length=8)),
            ],
        ),
    ]
